apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-app
        image: andrecarmo02/app-html:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
