version: "3.5"

x-deploy: &template-deploy
  replicas: 1
  restart_policy:
    condition: on-failure
  update_config:
    parallelism: 1
    delay: 10s

  web:
    image: httpd:alpine3.16
    networks:
      - "app-network"
    volumes:
      - '/data/app:/usr/local/apache2/htdocs/'      
    deploy: 
      <<: *template-deploy
      replicas: 1
    ports:
      - "80:80"
      - "843:443"
networks: 
  app-network:
    external: true