apiVersion: v1
kind: Pod
metadata:
  name: app-html
  labels:
    name: app-html
spec:
  containers:
    - name: app-html
      image: zabbix/zabbix-server-mysql:alpine-trunk
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 10050
