apiVersion: v1
kind: Pod
metadata:
  name: myapp-php
  labels:
    name: myapp-php
spec:
  containers:
  - name: myapp-php
    image: andrecarmo02/app3:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-php-service
spec:
  type: NodePort
  selector:
    app: myapp-php
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
