version: '3.8'

services:
  mysqlsrv:
    image: mysql:5.7
    env_file: 
      - ./envs/mysql.envs
    ports:
      - 3306:3306
    volumes:
      - /data/mysql-app:/var/lib/mysql
    networks:
      - minha-rede
  
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge